version: "3.8"
services:
  react:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
      # node_modulesをキャッシュ
      - front_node_modules:/workspace/node_modules
volumes:
  - front_node_modules
